cppguide.pdf: compile.sh cppguide.md
	./compile.sh cppguide.md

compile.sh:
	curl \
		--output "compile.sh" \
		"https://raw.githubusercontent.com/Genrep-Software/document-template/master/compile.sh"
